[workspace]
authors = ["syjung <jsy960608@gmail.com>"]
channels = ["conda-forge"]
name = "troppo_env"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.9"
pip = "*"

[pypi-dependencies]
troppo = { git = "https://github.com/BioSystemsUM/troppo.git" }
cobamp = "==0.2.1"
cobra = "==0.24.0"
numpy = "*"
pandas = "*"
matplotlib = "*"
